### ISSUE TITLE
Great tool, but i´m not smart enough to get it work correct :-)

### ISSUE THREAD

**Issue by odeldodel** [josephdadams/TallyArbiter-Pimoroni-Blinkt-listener#2]
Hi,
TallyArbiter is a great way to realize Tally lights.
I run it on an Raspberry Pi4. The connection to an web client works fine. As Tally Lights for the cameras i´d like tu use several Pi4 with Pimoroni Blinkt LED stripes. The attached video shows my problem. I hope someone can help me.

Best regards
Daniel

https://user-images.githubusercontent.com/82779661/115568615-c1912b80-a2bc-11eb-8a9c-e496968f1f90.mov

**Comment by josephdadams** [comment]
Yes this is a known bug with this client that I have not had time to look into.

**Comment by odeldodel** [comment]
Thank you for your fast response. Meanwhile, I figured out, if you toggle between preview/program/off and press "flash" on the settings page, the device shows the correct color after the flash. Let me know if I can help you in any way with this issue.

**Comment by josephdadams** [comment]
I believe this is fixed in the latest commit. If not, please re-open this issue and we can investigate further.
